FROM python:3.10
EXPOSE 8501
WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit", "run", "image_classification.py", "--server.port=8501", "--server.address=0.0.0.0"]